// Tech Review Video - GSAP Animations
// Auto-generated by compose-video.ts
 
const tl = gsap.timeline({ paused: true });
 

  // ─── Intro (0s - 14.2s) ───
  // Pulsing rings
  tl.fromTo('.intro-ring-1', { scale: 0, opacity: 0 }, { scale: 1, opacity: 0.3, duration: 1.5, ease: 'power2.out' }, 0);
  tl.fromTo('.intro-ring-2', { scale: 0, opacity: 0 }, { scale: 1, opacity: 0.2, duration: 2, ease: 'power2.out' }, 0.3);
  tl.fromTo('.intro-ring-3', { scale: 0, opacity: 0 }, { scale: 1, opacity: 0.1, duration: 2.5, ease: 'power2.out' }, 0.6);
  // Particles
  tl.fromTo('.particle', { opacity: 0, scale: 0 }, { opacity: 0.6, scale: 1, duration: 0.8, stagger: { each: 0.1, from: 'random' }, ease: 'back.out(1.5)' }, 0.5);
  tl.to('.particle', { y: '-=30', x: '+=15', duration: 14.210625, ease: 'none', stagger: { each: 0.2 } }, 0);
  // Content
  tl.fromTo('.intro-badge', { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6 }, 0.3);
  tl.fromTo('.intro-title', { opacity: 0, scale: 0.85 }, { opacity: 1, scale: 1, duration: 0.8, ease: 'back.out(1.5)' }, 0.6);
  tl.fromTo('.intro-date', { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.5 }, 1.2);
  tl.fromTo('.intro-author', { opacity: 0 }, { opacity: 1, duration: 0.5 }, 1.6);
  tl.fromTo('.intro-loader-fill', { width: '0%' }, { width: '100%', duration: 14.210625, ease: 'none' }, 0);
  tl.to('.scene-intro .scene-content', { opacity: 0, duration: 0.6 }, 13.410625);
  tl.to('.intro-ring', { opacity: 0, duration: 0.5 }, 13.410625);
  tl.to('.particle', { opacity: 0, duration: 0.3 }, 13.710625);
  tl.set('#subtitle-text', { innerText: "Chào mừng các bạn đã" }, 0.30);
  tl.set('#subtitle-text', { innerText: "đến với kênh của mình!" }, 1.57);
  tl.set('#subtitle-text', { innerText: "Hôm nay," }, 3.01);
  tl.set('#subtitle-text', { innerText: "mình sẽ giới thiệu về" }, 3.56);
  tl.set('#subtitle-text', { innerText: "OpenClaw - một trợ lý" }, 4.92);
  tl.set('#subtitle-text', { innerText: "AI tự vận hành đang" }, 6.27);
  tl.set('#subtitle-text', { innerText: "gây bão toàn cầu." }, 7.46);
  tl.set('#subtitle-text', { innerText: "Hãy cùng khám phá những" }, 8.58);
  tl.set('#subtitle-text', { innerText: "tính năng nổi bật và" }, 10.09);
  tl.set('#subtitle-text', { innerText: "những điều thú vị mà" }, 11.36);
  tl.set('#subtitle-text', { innerText: "OpenClaw mang lại!" }, 12.64);
  tl.set('#subtitle-text', { innerText: '' }, 13.91);

  // ─── TOC (14.210625s - 30.9s) ───
  tl.fromTo('.toc-header', { opacity: 0, y: -30 }, { opacity: 1, y: 0, duration: 0.6 }, 14.410625);
  tl.fromTo('.toc-line', { height: 0 }, { height: '100%', duration: 15.218375000000002, ease: 'power2.inOut' }, 14.710625);
  tl.fromTo('#toc-item-1', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'back.out(1.3)' }, 15.01);
  tl.fromTo('#toc-item-2', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'back.out(1.3)' }, 16.21);
  tl.fromTo('#toc-item-3', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'back.out(1.3)' }, 17.41);
  tl.fromTo('#toc-item-4', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'back.out(1.3)' }, 18.61);
  tl.to('.toc-content', { opacity: 0, duration: 0.5 }, 30.329);
  tl.set('#subtitle-text', { innerText: "Trong video hôm nay," }, 14.51);
  tl.set('#subtitle-text', { innerText: "chúng ta sẽ tìm hiểu" }, 16.09);
  tl.set('#subtitle-text', { innerText: "về OpenClaw." }, 17.57);
  tl.set('#subtitle-text', { innerText: "Một là," }, 18.59);
  tl.set('#subtitle-text', { innerText: "OpenClaw là gì?" }, 19.14);
  tl.set('#subtitle-text', { innerText: "Hai là," }, 20.35);
  tl.set('#subtitle-text', { innerText: "nguồn gốc phát triển của" }, 20.90);
  tl.set('#subtitle-text', { innerText: "OpenClaw." }, 22.76);
  tl.set('#subtitle-text', { innerText: "Ba là," }, 23.59);
  tl.set('#subtitle-text', { innerText: "cơ chế vận hành ‘Agentic" }, 24.05);
  tl.set('#subtitle-text', { innerText: "Workflow’." }, 25.90);
  tl.set('#subtitle-text', { innerText: "Và cuối cùng là," }, 26.83);
  tl.set('#subtitle-text', { innerText: "cách triển khai OpenClaw ổn" }, 28.04);
  tl.set('#subtitle-text', { innerText: "định." }, 30.17);
  tl.set('#subtitle-text', { innerText: '' }, 30.63);

  // ─── Section 1: OpenClaw là gì? (30.929000000000002s - 48.1s) ───
  tl.fromTo('#scene-section-1 .section-badge-top', { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.5 }, 31.129);
  // Mind map center node
  tl.fromTo('#mindmap-center-1', { scale: 0, opacity: 0 }, { scale: 1, opacity: 1, duration: 0.8, ease: 'back.out(1.5)' }, 31.429000000000002);
  // Branch node 1
  tl.fromTo('#scene-section-1 .mindmap-line-1', { strokeDashoffset: 400 }, { strokeDashoffset: 0, duration: 0.8, ease: 'power2.out' }, 32.43);
  tl.fromTo('#mindmap-node-1-1', { opacity: 0, scale: 0.5 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'back.out(1.5)' }, 32.83);
  // Branch node 2
  tl.fromTo('#scene-section-1 .mindmap-line-2', { strokeDashoffset: 400 }, { strokeDashoffset: 0, duration: 0.8, ease: 'power2.out' }, 33.23);
  tl.fromTo('#mindmap-node-1-2', { opacity: 0, scale: 0.5 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'back.out(1.5)' }, 33.63);
  // Branch node 3
  tl.fromTo('#scene-section-1 .mindmap-line-3', { strokeDashoffset: 400 }, { strokeDashoffset: 0, duration: 0.8, ease: 'power2.out' }, 34.03);
  tl.fromTo('#mindmap-node-1-3', { opacity: 0, scale: 0.5 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'back.out(1.5)' }, 34.43);
  // Keep-alive: floating nodes every 3s
  tl.to('#mindmap-center-1', { scale: 1.05, duration: 1.5, yoyo: true, repeat: 5, ease: 'sine.inOut' }, 33.929);
  tl.to('#scene-section-1 .mindmap-node', { y: '-=8', duration: 2, yoyo: true, repeat: 4, stagger: 0.3, ease: 'sine.inOut' }, 33.429);
  tl.to('#scene-section-1 .mindmap-node-dot', { boxShadow: '0 0 18px rgba(99,102,241,0.9)', duration: 1, yoyo: true, repeat: 8, stagger: 0.5, ease: 'sine.inOut' }, 33.929);
  tl.to('#scene-section-1 .mindmap-line', { opacity: 0.9, duration: 1.5, yoyo: true, repeat: 5, stagger: 0.4, ease: 'sine.inOut' }, 32.929);
  tl.to('#scene-section-1 .mindmap-content', { opacity: 0, duration: 0.6 }, 47.31175);
  tl.set('#subtitle-text', { innerText: "OpenClaw là trợ lý AI" }, 31.23);
  tl.set('#subtitle-text', { innerText: "tự động hóa công việc," }, 32.62);
  tl.set('#subtitle-text', { innerText: "với khả năng xử lý" }, 34.10);
  tl.set('#subtitle-text', { innerText: "1 triệu dữ liệu mỗi" }, 35.25);
  tl.set('#subtitle-text', { innerText: "giây." }, 36.48);
  tl.set('#subtitle-text', { innerText: "Nó giúp doanh nghiệp tiết" }, 36.89);
  tl.set('#subtitle-text', { innerText: "kiệm 30% thời gian với" }, 38.62);
  tl.set('#subtitle-text', { innerText: "tính năng phân tích dữ" }, 40.10);
  tl.set('#subtitle-text', { innerText: "liệu." }, 41.57);
  tl.set('#subtitle-text', { innerText: "Ví dụ," }, 41.98);
  tl.set('#subtitle-text', { innerText: "OpenClaw có thể tự động" }, 42.39);
  tl.set('#subtitle-text', { innerText: "gửi hàng trăm email và" }, 43.95);
  tl.set('#subtitle-text', { innerText: "sắp xếp lịch họp chỉ" }, 45.43);
  tl.set('#subtitle-text', { innerText: "trong vài giây!" }, 46.74);
  tl.set('#subtitle-text', { innerText: '' }, 47.81);

  // ─── Section 2: Nguồn gốc và hành trình phát triển của OpenClaw (48.11175s - 65.7s) ───
  tl.fromTo('#scene-section-2 .section-badge-top', { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.5 }, 48.31175);
  tl.fromTo('#section-title-2', { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6 }, 48.51175);
  tl.fromTo('#feature-card-2-1', { opacity: 0, rotateY: 90 }, { opacity: 1, rotateY: 0, duration: 0.7, ease: 'back.out(1.2)' }, 49.31);
  tl.fromTo('#feature-card-2-2', { opacity: 0, rotateY: 90 }, { opacity: 1, rotateY: 0, duration: 0.7, ease: 'back.out(1.2)' }, 50.11);
  tl.fromTo('#feature-card-2-3', { opacity: 0, rotateY: 90 }, { opacity: 1, rotateY: 0, duration: 0.7, ease: 'back.out(1.2)' }, 50.91);
  // Keep-alive: card glow pulse every 3s
  tl.to('#scene-section-2 .feature-card', { borderColor: 'rgba(99,102,241,0.3)', duration: 1.5, yoyo: true, repeat: 5, stagger: 0.4, ease: 'sine.inOut' }, 51.11175);
  tl.to('#scene-section-2 .feature-card-icon', { scale: 1.2, duration: 1, yoyo: true, repeat: 8, stagger: 0.5, ease: 'sine.inOut' }, 51.61175);
  tl.to('#scene-section-2 .feature-card-line', { width: 80, duration: 2, yoyo: true, repeat: 4, stagger: 0.3, ease: 'sine.inOut' }, 50.61175);
  tl.to('#scene-section-2 .cards-content', { opacity: 0, duration: 0.6 }, 64.912458);
  tl.set('#subtitle-text', { innerText: "Bắt đầu phát triển từ" }, 48.41);
  tl.set('#subtitle-text', { innerText: "năm 2021," }, 49.92);
  tl.set('#subtitle-text', { innerText: "OpenClaw đã phục vụ hơn" }, 50.63);
  tl.set('#subtitle-text', { innerText: "10 triệu lượt truy cập" }, 52.31);
  tl.set('#subtitle-text', { innerText: "mỗi tháng nhờ vào khả" }, 53.90);
  tl.set('#subtitle-text', { innerText: "năng phân tích ngữ nghĩa" }, 55.41);
  tl.set('#subtitle-text', { innerText: "xuất sắc." }, 57.18);
  tl.set('#subtitle-text', { innerText: "Tính năng này giúp nó" }, 57.89);
  tl.set('#subtitle-text', { innerText: "hiểu 90% câu hỏi người" }, 59.39);
  tl.set('#subtitle-text', { innerText: "dùng," }, 60.99);
  tl.set('#subtitle-text', { innerText: "rất cao so với các" }, 61.43);
  tl.set('#subtitle-text', { innerText: "trợ lý AI khác như" }, 62.67);
  tl.set('#subtitle-text', { innerText: "ChatGPT chỉ đạt 75%." }, 63.91);
  tl.set('#subtitle-text', { innerText: '' }, 65.41);

  // ─── Section 3: Cơ chế vận hành 'Agentic Workflow' của OpenClaw AI (65.712458s - 83.2s) ───
  tl.fromTo('#scene-section-3 .section-badge-top', { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.5 }, 65.912458);
  tl.fromTo('#section-title-3', { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6 }, 66.112458);
  tl.fromTo('#comp-row-3-1', { opacity: 0, x: -60 }, { opacity: 1, x: 0, duration: 0.6, ease: 'power3.out' }, 66.91);
  tl.to('#comp-row-3-1 .comp-bar-fill', { width: '85%', duration: 1, ease: 'power2.out' }, 67.21);
  tl.fromTo('#comp-row-3-1 .comp-check', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.3, ease: 'back.out(2)' }, 67.71);
  tl.fromTo('#comp-row-3-2', { opacity: 0, x: 60 }, { opacity: 1, x: 0, duration: 0.6, ease: 'power3.out' }, 67.71);
  tl.to('#comp-row-3-2 .comp-bar-fill', { width: '72%', duration: 1, ease: 'power2.out' }, 68.01);
  tl.fromTo('#comp-row-3-2 .comp-check', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.3, ease: 'back.out(2)' }, 68.51);
  tl.fromTo('#comp-row-3-3', { opacity: 0, x: -60 }, { opacity: 1, x: 0, duration: 0.6, ease: 'power3.out' }, 68.51);
  tl.to('#comp-row-3-3 .comp-bar-fill', { width: '90%', duration: 1, ease: 'power2.out' }, 68.81);
  tl.fromTo('#comp-row-3-3 .comp-check', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.3, ease: 'back.out(2)' }, 69.31);
  // Keep-alive: bar width pulse and row highlight every 3s
  tl.to('#scene-section-3 .comparison-row', { backgroundColor: 'rgba(99,102,241,0.08)', duration: 1.5, yoyo: true, repeat: 5, stagger: 0.5, ease: 'sine.inOut' }, 69.212458);
  tl.to('#scene-section-3 .comp-check', { scale: 1.2, duration: 0.8, yoyo: true, repeat: 8, stagger: 0.4, ease: 'sine.inOut' }, 69.712458);
  tl.to('#scene-section-3 .comparison-content', { opacity: 0, duration: 0.6 }, 82.373875);
  tl.set('#subtitle-text', { innerText: "OpenClaw AI sử dụng vòng" }, 66.01);
  tl.set('#subtitle-text', { innerText: "lặp OODA để dự đoán" }, 67.83);
  tl.set('#subtitle-text', { innerText: "và ra quyết định nhanh" }, 69.19);
  tl.set('#subtitle-text', { innerText: "chóng," }, 70.82);
  tl.set('#subtitle-text', { innerText: "giúp doanh nghiệp tăng doanh" }, 71.36);
  tl.set('#subtitle-text', { innerText: "thu 20%." }, 73.54);
  tl.set('#subtitle-text', { innerText: "Ngoài ra," }, 74.17);
  tl.set('#subtitle-text', { innerText: "triết lý BYOM cho phép" }, 74.90);
  tl.set('#subtitle-text', { innerText: "tùy chỉnh mô hình AI," }, 76.53);
  tl.set('#subtitle-text', { innerText: "giúp tối ưu hóa quy" }, 78.07);
  tl.set('#subtitle-text', { innerText: "trình làm việc hàng ngày" }, 79.43);
  tl.set('#subtitle-text', { innerText: "một cách hiệu quả hơn." }, 81.24);
  tl.set('#subtitle-text', { innerText: '' }, 82.87);

  // ─── Section 4: Triển khai OpenClaw ổn định 24/7 với VPS tại Vietnix (83.173875s - 100.2s) ───
  tl.fromTo('#scene-section-4 .section-badge-top', { opacity: 0, x: -30 }, { opacity: 1, x: 0, duration: 0.5 }, 83.373875);
  tl.fromTo('#section-title-4', { opacity: 0, y: 30 }, { opacity: 1, y: 0, duration: 0.6 }, 83.573875);
  tl.fromTo('#scene-section-4 .checklist-shield', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.8, ease: 'elastic.out(1, 0.5)' }, 83.77387499999999);
  tl.fromTo('#check-item-4-1', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'power3.out' }, 84.97);
  tl.to('#check-item-4-1 .check-path', { strokeDashoffset: 0, duration: 0.4, ease: 'power2.out' }, 85.37);
  tl.to('#check-item-4-1 .check-box', { borderColor: '#22c55e', background: 'rgba(34, 197, 94, 0.15)', duration: 0.3 }, 85.37);
  tl.fromTo('#check-item-4-2', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'power3.out' }, 85.97);
  tl.to('#check-item-4-2 .check-path', { strokeDashoffset: 0, duration: 0.4, ease: 'power2.out' }, 86.37);
  tl.to('#check-item-4-2 .check-box', { borderColor: '#22c55e', background: 'rgba(34, 197, 94, 0.15)', duration: 0.3 }, 86.37);
  tl.fromTo('#check-item-4-3', { opacity: 0, x: -40 }, { opacity: 1, x: 0, duration: 0.5, ease: 'power3.out' }, 86.97);
  tl.to('#check-item-4-3 .check-path', { strokeDashoffset: 0, duration: 0.4, ease: 'power2.out' }, 87.37);
  tl.to('#check-item-4-3 .check-box', { borderColor: '#22c55e', background: 'rgba(34, 197, 94, 0.15)', duration: 0.3 }, 87.37);
  // Keep-alive: shield pulse and item emphasis every 3s
  tl.to('#shield-icon-4', { scale: 1.1, duration: 1.5, yoyo: true, repeat: 5, ease: 'sine.inOut' }, 86.173875);
  tl.to('#scene-section-4 .checklist-item', { backgroundColor: 'rgba(34,197,94,0.06)', duration: 1.5, yoyo: true, repeat: 5, stagger: 0.4, ease: 'sine.inOut' }, 87.173875);
  tl.to('#scene-section-4 .check-box', { scale: 1.1, duration: 0.8, yoyo: true, repeat: 8, stagger: 0.3, ease: 'sine.inOut' }, 86.673875);
  tl.to('#scene-section-4 .checklist-content', { opacity: 0, duration: 0.6 }, 99.370875);
  tl.set('#subtitle-text', { innerText: "Triển khai OpenClaw trên VPS" }, 83.47);
  tl.set('#subtitle-text', { innerText: "tại Vietnix giúp đảm bảo" }, 85.49);
  tl.set('#subtitle-text', { innerText: "tính ổn định 24/7." }, 87.17);
  tl.set('#subtitle-text', { innerText: "Ví dụ," }, 88.44);
  tl.set('#subtitle-text', { innerText: "nó có thể xử lý" }, 88.86);
  tl.set('#subtitle-text', { innerText: "10.000 yêu cầu mỗi ngày," }, 89.78);
  tl.set('#subtitle-text', { innerText: "giúp doanh nghiệp tiết kiệm" }, 91.46);
  tl.set('#subtitle-text', { innerText: "thời gian đáng kể và" }, 93.40);
  tl.set('#subtitle-text', { innerText: "nâng cao hiệu suất làm" }, 94.74);
  tl.set('#subtitle-text', { innerText: "việc." }, 96.26);
  tl.set('#subtitle-text', { innerText: "Hoàn toàn phù hợp cho" }, 96.68);
  tl.set('#subtitle-text', { innerText: "các doanh nghiệp bận rộn!" }, 98.11);
  tl.set('#subtitle-text', { innerText: '' }, 99.87);

  // ─── Summary (100.170875s - 115.3s) ───
  tl.fromTo('.summary-header', { opacity: 0, y: -30 }, { opacity: 1, y: 0, duration: 0.6 }, 100.370875);
  tl.fromTo('.summary-dashboard', { opacity: 0 }, { opacity: 1, duration: 0.4 }, 100.670875);
  tl.fromTo('.radial-stat', { opacity: 0, scale: 0.5 }, { opacity: 1, scale: 1, duration: 0.6, stagger: 0.2, ease: 'back.out(1.5)' }, 100.77087499999999);
  // Radial ring animations
  tl.to('.radial-fill-1', { strokeDashoffset: 81.75, duration: 1.5, ease: 'power2.out' }, 101.170875);
  tl.to('.radial-fill-2', { strokeDashoffset: 130.8, duration: 1.5, ease: 'power2.out' }, 101.370875);
  tl.to('.radial-fill-3', { strokeDashoffset: 179.85, duration: 1.5, ease: 'power2.out' }, 101.570875);
  tl.to('.radial-fill-4', { strokeDashoffset: 147.14999999999998, duration: 1.5, ease: 'power2.out' }, 101.77087499999999);
  // Keep-alive: radial stat pulse every 3s
  tl.to('.radial-stat', { scale: 1.05, duration: 1.5, yoyo: true, repeat: 5, stagger: 0.3, ease: 'sine.inOut' }, 103.170875);
  tl.to('.radial-number', { color: '#a5b4fc', duration: 1, yoyo: true, repeat: 7, stagger: 0.4, ease: 'sine.inOut' }, 103.670875);
  tl.to('.summary-content', { opacity: 0, duration: 0.5 }, 114.463833);
  tl.set('#subtitle-text', { innerText: "Tóm lại," }, 100.47);
  tl.set('#subtitle-text', { innerText: "OpenClaw là một trợ lý" }, 101.07);
  tl.set('#subtitle-text', { innerText: "AI tự động hóa vượt" }, 102.63);
  tl.set('#subtitle-text', { innerText: "trội," }, 103.92);
  tl.set('#subtitle-text', { innerText: "với khả năng xử lý" }, 104.35);
  tl.set('#subtitle-text', { innerText: "dữ liệu nhanh chóng," }, 105.56);
  tl.set('#subtitle-text', { innerText: "cải thiện quy trình làm" }, 107.03);
  tl.set('#subtitle-text', { innerText: "việc và đảm bảo ổn" }, 108.67);
  tl.set('#subtitle-text', { innerText: "định 24/7." }, 109.87);
  tl.set('#subtitle-text', { innerText: "Đây chính là công cụ" }, 110.65);
  tl.set('#subtitle-text', { innerText: "đáng để thử cho các" }, 112.03);
  tl.set('#subtitle-text', { innerText: "doanh nghiệp hiện đại!" }, 113.32);
  tl.set('#subtitle-text', { innerText: '' }, 114.96);

  // ─── Closing (115.26383299999999s - 122.6s) ───
  tl.fromTo('.closing-card', { opacity: 0, y: 50, scale: 0.92 }, { opacity: 1, y: 0, scale: 1, duration: 0.8, ease: 'back.out(1.3)' }, 115.463833);
  tl.fromTo('#closing-title', { opacity: 0, y: -20 }, { opacity: 1, y: 0, duration: 0.5 }, 115.76383299999999);
  tl.fromTo('#closing-text', { opacity: 0, y: 15 }, { opacity: 1, y: 0, duration: 0.5 }, 116.06383299999999);
  // Social CTA buttons - spring entrance
  tl.fromTo('#cta-like', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'elastic.out(1, 0.4)' }, 116.463833);
  tl.fromTo('#cta-subscribe', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'elastic.out(1, 0.4)' }, 116.76383299999999);
  tl.fromTo('#cta-share', { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.5, ease: 'elastic.out(1, 0.4)' }, 117.06383299999999);
  tl.fromTo('.closing-signature', { opacity: 0, width: 0 }, { opacity: 0.8, width: 250, duration: 0.8, ease: 'power2.out' }, 117.463833);
  // Keep-alive: CTA button bounce every 3s
  tl.to('.cta-btn', { y: -5, duration: 0.8, yoyo: true, repeat: 3, stagger: 0.2, ease: 'sine.inOut' }, 118.26383299999999);
  tl.to('.cta-icon', { scale: 1.15, duration: 0.6, yoyo: true, repeat: 4, stagger: 0.3, ease: 'sine.inOut' }, 118.76383299999999);
  tl.to('.closing-card', { opacity: 0, scale: 0.9, duration: 0.8, ease: 'power2.in' }, 121.601333);
  tl.set('#subtitle-text', { innerText: "Cảm ơn các bạn đã" }, 115.56);
  tl.set('#subtitle-text', { innerText: "theo dõi video." }, 116.42);
  tl.set('#subtitle-text', { innerText: "Đừng quên like và subscribe" }, 117.28);
  tl.set('#subtitle-text', { innerText: "để không bỏ lỡ những" }, 118.80);
  tl.set('#subtitle-text', { innerText: "video công nghệ thú vị" }, 119.86);
  tl.set('#subtitle-text', { innerText: "tiếp theo!" }, 121.05);
  tl.set('#subtitle-text', { innerText: "Hẹn gặp lại!" }, 121.64);
  tl.set('#subtitle-text', { innerText: '' }, 122.30);
 
// Register timeline for HyperFrames
window.__timelines = window.__timelines || {};
window.__timelines["tech-review"] = tl;
